version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=db_app
      - POSTGRES_PASSWORD=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/mysql